---
# mikanos-buildで必要とされているパッケージ (llvm-dev, lld, clang は 14 ではなく 18にしている)
# https://github.com/uchan-nos/mikanos-build/blob/master/devenv/ansible_provision.yml#L4
- hosts: all
  tasks:
    - name: set llvm 19 as default
      alternatives:
        name: "{{ item }}"
        link: "/usr/bin/{{ item }}"
        path: "/usr/bin/{{ item }}-19"
      with_items:
        - llvm-PerfectShuffle
        - llvm-ar
        - llvm-as
        - llvm-bcanalyzer
        - llvm-cat
        - llvm-cfi-verify
        - llvm-config
        - llvm-cov
        - llvm-c-test
        - llvm-cvtres
        - llvm-cxxdump
        - llvm-cxxfilt
        - llvm-diff
        - llvm-dis
        - llvm-dlltool
        - llvm-dwarfdump
        - llvm-dwp
        - llvm-exegesis
        - llvm-extract
        - llvm-lib
        - llvm-link
        - llvm-lto
        - llvm-lto2
        - llvm-mc
        - llvm-mca
        - llvm-modextract
        - llvm-mt
        - llvm-nm
        - llvm-objcopy
        - llvm-objdump
        - llvm-opt-report
        - llvm-pdbutil
        - llvm-profdata
        - llvm-ranlib
        - llvm-rc
        - llvm-readelf
        - llvm-readobj
        - llvm-rtdyld
        - llvm-size
        - llvm-split
        - llvm-stress
        - llvm-strings
        - llvm-strip
        - llvm-symbolizer
        - llvm-tblgen
        - llvm-undname
        - llvm-xray
        - ld.lld
        - lld-link
        - clang
        - clang++
        - clang-cpp
